Repository polito-inginf/inginf_bot, pull requests merged in 2020-09, with the labels that each got.

#2 Syntax correction
  .github/CONTRIBUTING.md
  .gitignore
  index.php
  inginf_bot.service
  log/inginf_bot.log
Labels: documentation, enhancement

#3 Refactoring of the code
  .github/CONTRIBUTING.md
Labels: documentation

#5 Added the guide to install the dependencies
  README.md
Labels: documentation

#10 Initial rewrite
  basefunctions.php
  composer.json
  constants.php
  header.php
  index.php
  inginf_bot.sql
  variables.php
Labels: rewrite

#11 Code rewrite
  README.md
  basefunctions.php
  composer.json
  constants.php
  header.php
  index.php
  inginf_bot.sql
  variables.php
Labels: rewrite
