Repository polito-inginf/inginf_bot, pull requests merged in 2020-10, with the labels that each got.

#14 Security/only admins
  .gitignore
  basefunctions.php
  index.php
  logger.php
Labels: duplicate, enhancement, fix

#15 Refactoring of the code
  .gitignore
  basefunctions.php
  constants.php
  header.php
  index.php
  logger.php
  private_example.php
  variables.php
Labels: enhancement, fix, rewrite

#20 Features/basefunctions
  basefunctions.php
  constants.php
Labels: enhancement

#21 rewrite/sendMessage
  basefunctions.php
Labels: rewrite

#22 Rewrite/camel case
  .github/CONTRIBUTING.md
  LICENSE
  README.md
  basefunctions.php
  constants.php
  header.php
  index.php
  logger.php
  private_example.php
  variables.php
Labels: documentation, enhancement, fix, rewrite

#23 ♻️ Rewriting bitmask constants using the shift operator (<<)
  constants.php
Labels: rewrite

#24 Features/basefunctions
  basefunctions.php
  constants.php
Labels: enhancement, hacktoberfest-accepted, rewrite

#26 Implemented new Bot API calls
  .github/SECURITY.md
  .github/workflows/averacode-analysis.yml
  .github/workflows/checkmarx-analysis.yml
  .github/workflows/codacy-analysis.yml
  .github/workflows/fortify-analysis.yml
  .github/workflows/shiftleft-analysis.yml
  basefunctions.php
  constants.php
  inginf_bot.sql
  logger.php
  private_example.php
Labels: enhancement, hacktoberfest-accepted, rewrite

#27 Features/basefunctions
  basefunctions.php
Labels: enhancement, hacktoberfest-accepted

#28 Rewrite the code
  basefunctions.php
  logger.php
Labels: bug, fix, hacktoberfest-accepted, rewrite

#29 Added some check and rewrited/refactored the code
  .github/CONTRIBUTING.md
  BotAPIfunctions.php
  functions.php
  index.php
Labels: enhancement, hacktoberfest-accepted, rewrite
